services:
  development:
    build: .
    image: twirp-example-dev
    container_name: twirp-example-dev
    stdin_open: true
    tty: true
    volumes:
      - .:/twirp-example
    profiles:
      - development
    depends_on:
      - dynamodb-local

  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./.docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    profiles:
      - development
